[package]
name = "portable-storage-utils"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
license = "Apache-2.0"
include = ["LICENSE"]
edition = "2018"

[dependencies]
bytes = "0.6"
serde = "1"
uuid = "0.8"
